server.port=8090
spring.datasource.url= jdbc:postgresql://localhost:5432/smart-api-gym-mat
spring.datasource.username=postgres
spring.datasource.password=Supersayayin21

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect